project:
  type: website

lang: es
date-format: "[Xalapa, Ver.,] D [de] MMMM, YYYY"

website:
  title: "Ciencia Abierta"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css

execute: 
  freeze: true

